kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: golang:1.25-alpine
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go build -o go_app
    volumes:
      - name: go_pkg
        path: /go/pkg/mod
    when:
      ref:
        - refs/tags/*+build
        - refs/tags/*+release

  - name: containerization
    image: plugins/docker
    volumes:
      - name: docker_data
        path: /var/lib/docker
      - name: docker_socket
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      registry: registry.op.tiaozhan.com
      repo: registry.op.tiaozhan.com/${DRONE_REPO_NAME,,}
      dockerfile: .deploy/Dockerfile
      tags:
        - latest
        - ${DRONE_SEMVER_SHORT}-${DRONE_COMMIT_SHA:0:8}
      cache_from:
        - registry.op.tiaozhan.com/${DRONE_REPO_NAME,,}:latest
      daemon_off: true
    when:
      ref:
        - refs/tags/*+build
        - refs/tags/*+release

  - name: deploy
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.op.tiaozhan.com
      - docker compose -f .deploy/docker-compose.yml -p $APP_NAME stop
      - docker compose -f .deploy/docker-compose.yml -p $APP_NAME rm -f
      - docker compose -f .deploy/docker-compose.yml -p $APP_NAME pull
      - docker compose -f .deploy/docker-compose.yml -p $APP_NAME up -d
    volumes:
      - name: docker_data
        path: /var/lib/docker
      - name: docker_socket
        path: /var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      APP_NAME: ${DRONE_REPO_NAME,,}
      APP_PORT:
        from_secret: APP_PORT
      APP_SECRET:
        from_secret: APP_SECRET
      APP_MYSQL_HOST:
        from_secret: APP_MYSQL_HOST
      APP_MYSQL_PORT: 3306
      APP_MYSQL_NAME:
        from_secret: APP_MYSQL_NAME
      APP_MYSQL_USER:
        from_secret: APP_MYSQL_USER
      APP_MYSQL_PASS:
        from_secret: APP_MYSQL_PASS
      APP_ALLOW_ORIGINS:
        from_secret: APP_ALLOW_ORIGINS
      APP_ALLOW_HEADERS: Origin|Content-Length|Content-Type|Authorization|x-session-id|x-http-method-override
      APP_URL_HOST:
        from_secret: APP_URL_HOST
      APP_URL_PORT: 8088
      OSS_USE_LOCAL: true
      OSS_ACCESS_KEY_ID: ""
      OSS_ACCESS_KEY_SECRET: ""
      OSS_REGION: cn-hangzhou
      OSS_BUCKET_NAME: ""
      AUTO_APPROVAL: comment
      Oauth_Base: https://oauth.tiaozhan.com
      Client_ID: tu_xun
      Client_Secret:
        from_secret: CLIENT_SECRET
      FE_ORIGIN:
        from_secret: FE_ORIGIN
      ADMIN_ORIGIN:
        from_secret: ADMIN_ORIGIN
      HOT_LIKE_WEIGHT: 2
      HOT_ATTEMPT_WEIGHT: 1
      ONLINE_CALLBACK:
        from_secret: ONLINE_CALLBACK
    when:
      ref:
        - refs/tags/*+deploy
        - refs/tags/*+release

volumes:
  - name: docker_data
    host:
      path: /var/lib/docker
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: go_pkg
    host:
      path: /tz-master-data/app_cache/go

trigger:
  event:
    - tag
